Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 712, in main
    esp = esp or get_default_connected_device(
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/__init__.py", line 1024, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/loader.py", line 678, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/loader.py", line 563, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/reset.py", line 103, in __call__
    self._setDTR(True)  # Set IO0
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/esptool/reset.py", line 37, in _setDTR
    self.port.setDTR(state)
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/serialutil.py", line 603, in setDTR
    self.dtr = value
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/serialutil.py", line 473, in dtr
    self._update_dtr_state()
  File "/home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py", line 713, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/xiaowai/.espressif/python_env/idf5.1_py3.8_env/bin/python;;/home/xiaowai/exmnt/esp-hosted/esp_hosted_fg/esp/esp_driver/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32c6
  failed.



